name: CI

on:
  push:
  pull_request:

jobs:
  api-smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install root deps
        run: npm ci

      - name: Install server deps
        run: npm ci --prefix server

      - name: Run API smoke test
        run: node server/test_api.js
